# Create array

In [30]:
import numpy as np 

x = np.array([1,2,3,4,5])
array_arange = np.arange(0,10,2)
array_arange

array([0, 2, 4, 6, 8])

In [26]:
# 128 - 256 = -6
arr_zeros = np.zeros(10,dtype=np.int8) 
arr_zeros[0] = 128
arr_zeros

C:\Users\baher\AppData\Local\Temp\ipykernel_5368\1951760052.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr_zeros[0] = 128


array([-128,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int8)

In [8]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
arr_2d_ones = np.ones((3,4), dtype=np.uint8)
arr_2d_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [37]:
arr_random = np.random.randint(0,10,(2,5))
arr_random

array([[7, 2, 4, 2, 5],
       [2, 0, 7, 2, 6]])

In [38]:
arr_empty = np.empty(3)
arr_empty

array([ 0.00000000e+000,  7.47631186e-312, -0.00000000e+000])

# Attribues

In [39]:
arr_2d_ones.shape

(3, 4)

In [40]:
arr_2d_ones.size

12

In [42]:
arr_2d_ones.dtype

dtype('float64')

In [47]:
arr_2d_ones.ndim

2

# Arithmatic operations

In [48]:
myArr1 = np.array([1,2,3])
myArr2 = np.array([5,6,7])

myList = []
for i in range(3):
  myList.append(myArr1[i] + myArr2[i])
myList

[6, 8, 10]

In [49]:
myArr1 + myArr2

array([ 6,  8, 10])

In [50]:
myArr1 - myArr2

array([-4, -4, -4])

In [53]:
myArr1 / myArr2

array([0.2       , 0.33333333, 0.42857143])

In [55]:
myArr1 ** myArr2

array([   1,   64, 2187])

```python
myArr1 = np.array([1,2,3])
myArr2 = np.array([5,6,7])
```

In [56]:
myArr1 * myArr2

array([ 5, 12, 21])

In [57]:
myArr2d1 = np.array([[1,2],
                     [4,5]])

myArr2d2 = np.array([[2,3],
                     [5,7]])

In [58]:
print(myArr2d1)
print(myArr2d2)

[[1 2]
 [4 5]]
[[2 3]
 [5 7]]


In [59]:
myArr2d1 * myArr2d2

array([[ 2,  6],
       [20, 35]])

In [60]:
np.dot(myArr2d1,myArr2d2)

array([[12, 17],
       [33, 47]])

# Slicing

to Access Array

Array[Rows, Columns, Color] in image

In [80]:
arr_random = np.random.randint(0,9,(3,3))
arr_random

array([[8, 5, 8],
       [8, 1, 3],
       [1, 0, 4]])

In [84]:
arr_random[:,1]

array([5, 1, 0])

# reshaping

In [109]:
d1Array = np.arange(10)
d1Array = d1Array.reshape((2,5))
d1Array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# useful functions

In [97]:
np.sum(d1Array)

45

In [112]:
d1Array.sum(axis=1)

array([10, 35])

In [99]:
np.min(d1Array)

0

In [100]:
np.max(d1Array)

9

# mean, madian, sort, concatenate, std

In [104]:
part1 = np.array([1,2,3,4])
part2 = np.array([1,9,0,3])

np.concatenate((part2, part1))

array([1, 9, 0, 3, 1, 2, 3, 4])

In [117]:
evenSpace = np.linspace(2,10,num=5)
evenSpace

# 1.33

array([ 2.,  4.,  6.,  8., 10.])

In [125]:
n2 = part1[np.newaxis,:]
n2.shape

(1, 4)

In [128]:
np.random.rand(2,3)

array([[0.57396202, 0.53673836, 0.76063971],
       [0.92613091, 0.24055382, 0.21906278]])

# Condition

In [ ]:
npArray = np.array([1,2,3,4,5,6])
npArray

In [ ]:
npArray + 2 

In [ ]:
npArray < 2

In [ ]:
trueArray = npArray % 2 == 0
trueArray

[1,2,3,4,5,6]

[False,  True, False,  True, False,  True]

### Find Divisible number by 2 using loop

In [ ]:
s = []
for i in range(len(trueArray)):
  if trueArray[i]:
    s.append(npArray[i])

s = np.array(s)
s

### Find Divisible number by 2 using numpy

In [ ]:
npArray[trueArray]

### Another example

In [ ]:
true2 = npArray % 3 == 0
npArray[true2]

In [ ]:
# this is the same
npArray[npArray % 3 == 0]