In [17]:
import numpy as np
import skimage as ski

# Correlation

In [18]:
zeroArray_5 = np.zeros(5, dtype=np.uint8)
zeroArray_5[2] = 1
zeroArray_5

array([0, 0, 1, 0, 0], dtype=uint8)

Filter

In [19]:
correlation_filterSize= 5
correlation_filter = np.array([1,2,5,7,8], dtype=np.uint8)
correlation_filter

array([1, 2, 5, 7, 8], dtype=uint8)

In [20]:
correlation_newMatrixSize = zeroArray_5.size - correlation_filter.size + 1
correlation_newMatrix = np.zeros(correlation_newMatrixSize, dtype=np.uint8)
correlation_newMatrix

array([0], dtype=uint8)

In [21]:
for i in range(correlation_newMatrixSize):
    correlation_newMatrix[i] = np.dot(zeroArray_5[i:i+correlation_filterSize], correlation_filter)
correlation_newMatrix

array([5], dtype=uint8)

## bigger matrix

In [22]:
zeroArray_7 = np.zeros(7, dtype=np.uint8)
zeroArray_7[3] = 1
zeroArray_7

array([0, 0, 0, 1, 0, 0, 0], dtype=uint8)

In [23]:
correlation_newMatrixSize_7 = zeroArray_7.size - correlation_filter.size + 1
correlation_newMatrix_7 = np.zeros(correlation_newMatrixSize_7, dtype=np.uint8)
correlation_newMatrix_7

array([0, 0, 0], dtype=uint8)

In [24]:
for i in range(correlation_newMatrixSize_7):
    correlation_newMatrix_7[i] = np.dot(zeroArray_7[i:i+correlation_filterSize], correlation_filter)
correlation_newMatrix_7

array([7, 5, 2], dtype=uint8)

# Convolution

In [25]:
convolution_filter = correlation_filter[::-1]
convolution_filter

array([8, 7, 5, 2, 1], dtype=uint8)

In [26]:
convolution_newMatrixSize_7 = zeroArray_7.size - convolution_filter.size + 1
convolution_newMatrix_7 = np.zeros(convolution_newMatrixSize_7, dtype=np.uint8)
convolution_newMatrix_7

array([0, 0, 0], dtype=uint8)

In [27]:
for i in range(convolution_newMatrixSize_7):
    convolution_newMatrix_7[i] = np.dot(zeroArray_7[i:i+correlation_filterSize], convolution_filter)
convolution_newMatrix_7

array([2, 5, 7], dtype=uint8)

# Padding

## For 1D

For 5 matrix

In [37]:
correlation_newMatrix_paddingSize = int(correlation_filterSize/2)
correlation_newMatrix_padding = np.pad(zeroArray_5, correlation_newMatrix_paddingSize, mode='constant')
correlation_newMatrix_padding

array([0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=uint8)

In [39]:
NewMatrix_5 = np.zeros(zeroArray_5.size, dtype=np.uint8)
NewMatrix_5

array([0, 0, 0, 0, 0], dtype=uint8)

In [41]:
for i in range(zeroArray_5.size):
  NewMatrix_5[i] = np.dot(correlation_newMatrix_padding[i:i+correlation_filterSize], correlation_filter)
NewMatrix_5

array([8, 7, 5, 2, 1], dtype=uint8)

## For 2D

In [46]:
correlation_2dMatrixSize_3 = (3,3)
correlation_2dMatrix_3 = np.zeros(correlation_2dMatrixSize_3, dtype=np.uint8)
correlation_2dMatrix_3[1,1] = 1
correlation_2dMatrix_3

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=uint8)

In [47]:
correlation_2dPadding_3 = np.pad(correlation_2dMatrix_3, 2, mode='constant')
correlation_2dPadding_3

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [52]:
correlation_2dFilter_5 = np.random.randint(0, 10, (5,5), dtype=np.uint8)
correlation_2dFilter_5

array([[7, 3, 3, 9, 0],
       [3, 4, 0, 5, 3],
       [1, 2, 6, 5, 1],
       [5, 3, 1, 0, 7],
       [3, 3, 8, 0, 1]], dtype=uint8)

In [55]:
correlation_2dNewMatrix_3 = np.zeros(correlation_2dMatrixSize_3, dtype=np.uint8)

for i in range(correlation_2dMatrixSize_3[0]):
    for j in range(correlation_2dMatrixSize_3[1]):
        correlation_2dNewMatrix_3[i,j] = np.sum(correlation_2dPadding_3[i:i+correlation_filterSize, j:j+correlation_filterSize] * correlation_2dFilter_5)
correlation_2dNewMatrix_3

array([[0, 1, 3],
       [5, 6, 2],
       [5, 0, 4]], dtype=uint8)