# Import library

In [1]:
import numpy as np

## Creat Numpy array

### Aranged Number

In [10]:
arangeArray = np.arange(10)
print(f"Arange array\n{arangeArray}")

Arange array
[0 1 2 3 4 5 6 7 8 9]


### Zero Array

#### 1D

In [9]:
zeroArray = np.zeros(3)
print(f"1D zero array\n{zeroArray}")

1D zero array
[0. 0. 0.]


#### 2D

In [8]:
zeroArray = np.zeros((3,4))
print(f"2D zero array\n{zeroArray}")

2D zero array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### N-D

In [7]:
zeroArray = np.zeros((3,4,3))
print(f"N-D zero array\n{zeroArray}")

N-D zero array
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### Random Array from 0 to 1

In [17]:
randomArray = np.random.rand(3, 4)
print(f"2D random array\n{randomArray}")

2D random array
[[0.7030942  0.1605399  0.48502663 0.84637011]
 [0.15564038 0.98344133 0.87652133 0.40928926]
 [0.93021637 0.40428911 0.51320056 0.66408549]]


### Random array from 0 to n

In [20]:
randomArrayInt = np.random.randint(0, 256, (3,4))
print(f"2D random array\n{randomArrayInt}")

2D random array
[[152 233 250  36]
 [ 12  83   3  11]
 [138 247 127  53]]


### From List

In [21]:
listArray = [1, 2, 3, 4, 5]
print(f"numpy array from list\n{arangeArray}")

numpy array from list
[0 1 2 3 4 5 6 7 8 9]


# Numpy datatype

### Int

In [28]:
int_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(f"Integer array:\n{int_array}\nType: {int_array.dtype}")

Integer array:
[1 2 3 4 5]
Type: int32


### Uint

In [27]:
uint_array = np.array([1, 2, 3, 4, 5], dtype=np.uint8)
print(f"Integer array:\n{int_array}\nType: {uint_array.dtype}")

Integer array:
[1 2 3 4 5]
Type: uint8


### Float

In [29]:
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)
print(f"Float array:\n{float_array}\nType: {float_array.dtype}")

Float array:
[1.1 2.2 3.3 4.4 5.5]
Type: float64


### Complex

In [30]:
complex_array = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)
print(f"Complex array:\n{complex_array}\nType: {complex_array.dtype}")

Complex array:
[1.+2.j 3.+4.j 5.+6.j]
Type: complex128


# Access numpy

In [31]:
nuArray = np.array([ [100,120,150],
                       [200,210,250],
                       [300,320,350] ])

## Access one row

In [32]:
nuArray[1]

array([200, 210, 250])

## Access one element

In [33]:
nuArray[2,1]

320

# Access range of elements

In [34]:
nuArray[1, 1:3]

array([210, 250])

## Access one row (Alternatve)

In [35]:
nuArray[1, :]

array([200, 210, 250])

## Access on column

In [36]:
nuArray[:,0]

array([100, 200, 300])

# Operation

# Arithmetic

In [39]:
newArr = nuArray + 20
print(f"Addition\n{newArr}\n")
newArr = nuArray * 20
print(f"Mul\n{newArr}")


Addition
[[120 140 170]
 [220 230 270]
 [320 340 370]]

Mul
[[2000 2400 3000]
 [4000 4200 5000]
 [6000 6400 7000]]


## Logic

In [40]:
h = nuArray > 100
newArr[h] = 0
newArr

array([[2000,    0,    0],
       [   0,    0,    0],
       [   0,    0,    0]])